export const REGISTER__START = "REGISTER__START";
export const REGISTER__SUCCESS = "REGISTER__SUCCESS";
export const REGISTER__FAILED = "REGISTER__FAILED";

export const LOGIN__START = "LOGIN__START";
export const LOGIN__SUCCESS = "LOGIN__SUCCESS";
export const LOGIN__FAILED = "LOGIN__FAILED";

// export const SET__INIT = "SET_INIT";

export const LOGOUT__INIT = "LOGOUT_INIT";

// export const CREATE__TESTIMONY__START = "CREATE__TESTIMONY__START";
// export const CREATE__TESTIMONY__SUCCESS = "CREATE__TESTIMONY__SUCCESS";
// export const CREATE__TESTIMONY__FAILED = "CREATE__TESTIMONY__FAILED";


// export const FETCH__TESIMONY__START = "FETCH__TESTIMONY__START"
// export const FETCH__TESIMONY__SUCCESS = "FETCH__TESTIMONY__SUCCESS"
// export const FETCH__TESIMONY__FAILED = "FETCH__TESTIMONY__FAILED"